# Final Netlify configuration with explicit function declarations
[build]
  command = "playwright install chromium"
  publish = "."

# This section explicitly tells Netlify about BOTH functions.
[functions]
  included_files = ["netlify/functions/**"]

  # Explicitly declare our main intelligence engine
  [functions.fetch_intel]
    runtime = "python"

  # Explicitly declare our simple test function
  [functions.hello]
    runtime = "python"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
