# Final Netlify configuration for a Python Playwright function
[build]
  publish = "."
  command = "playwright install chromium"

[functions]
  directory = "netlify/functions/"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
