# Final Netlify configuration with explicit function declaration
[build]
  command = "playwright install chromium"
  publish = "."

# This section explicitly tells Netlify about our function.
[functions]
  included_files = ["!node_modules/**"] # A standard optimization
  [functions.fetch_intel]
    # This ensures our function is included in the deployment.

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
